name: Docker Health Check
description: Checks the health of a Docker container
author: Michael Stringer
branding:
  color: blue
  icon: activity

inputs:
  container:
    description: Name of the container to check
    required: true
  require-status:
    description: Container status to require or wait for
    required: false
  require-healthy:
    description: If true then require the container to be healthy or wait until healthy
    required: false
    default: 'false'
  wait-time:
    description: Maximum number of seconds to wait for container to reach required status (in seconds)
    required: false
    default: '0'

outputs:
  status:
    description: Current status of the container
  healthy:
    description: true if the container is healthy

runs:
  using: node16
  main: dist/index.js
